//
//  TrueTypeOutlineTests.swift
//  CeolKitSVGRendererTests
//
//  Issue #189: `OpenTypeFont` reads TrueType (`glyf`) outlines and font collections.
//
//  The fixtures and the reference outlines they are checked against are generated by
//  Resources/truetype-fixtures.py; see the script for what each glyph exercises.
//

import Foundation
import Testing
@testable import CeolKitSVGRenderer
#if canImport(CoreText)
import CoreText
#endif

@Suite("TrueType outlines and font collections (#189)")
struct TrueTypeOutlineTests {

    // MARK: - Fixtures

    private static func fixture(_ name: String, _ ext: String) throws -> Data {
        let url = try #require(Bundle.module.url(forResource: name, withExtension: ext))
        return try Data(contentsOf: url)
    }

    private struct Reference: Decodable {
        let unitsPerEm: Int
        let indexToLocFormat: Int
        let fsType: Int
        let postScriptName: String
        let glyphs: [String: Glyph]

        struct Glyph: Decodable {
            let name: String
            let advance: Double
            let segments: [[Segment]]
        }

        /// One element of a recorded segment: its command letter, or a coordinate.
        enum Segment: Decodable {
            case command(String)
            case number(Double)

            init(from decoder: Decoder) throws {
                let value = try decoder.singleValueContainer()
                if let string = try? value.decode(String.self) {
                    self = .command(string)
                } else {
                    self = .number(try value.decode(Double.self))
                }
            }
        }
    }

    private static func references() throws -> [String: Reference] {
        try JSONDecoder().decode([String: Reference].self,
                                 from: try fixture("truetype-reference", "json"))
    }

    /// A recorded segment as the ``GlyphPath`` segment it stands for.
    private static func segment(_ recorded: [Reference.Segment]) throws -> GlyphPath.Segment {
        guard case .command(let command)? = recorded.first else {
            throw OpenTypeError.malformedGlyph("reference segment has no command")
        }
        let n = recorded.dropFirst().compactMap { element -> Double? in
            if case .number(let v) = element { return v }
            return nil
        }
        let point = { (i: Int) in GlyphPath.Point(x: n[i], y: n[i + 1]) }
        switch command {
        case "M": return .move(to: point(0))
        case "L": return .line(to: point(0))
        case "Q": return .quadCurve(control: point(0), to: point(2))
        case "Z": return .close
        default:  throw OpenTypeError.malformedGlyph("unknown reference command \(command)")
        }
    }

    private static func points(of segment: GlyphPath.Segment) -> [GlyphPath.Point] {
        switch segment {
        case .move(let p), .line(let p):         return [p]
        case .quadCurve(let c, let p):           return [c, p]
        case .curve(let c1, let c2, let p):      return [c1, c2, p]
        case .close:                             return []
        }
    }

    private static func sameKind(_ a: GlyphPath.Segment, _ b: GlyphPath.Segment) -> Bool {
        switch (a, b) {
        case (.move, .move), (.line, .line), (.quadCurve, .quadCurve), (.curve, .curve),
             (.close, .close): return true
        default: return false
        }
    }

    private func expectMatches(_ path: GlyphPath, _ expected: [GlyphPath.Segment],
                               _ label: String,
                               sourceLocation: SourceLocation = #_sourceLocation) {
        #expect(path.segments.count == expected.count,
                "\(label): \(path.segments.count) segments, expected \(expected.count)",
                sourceLocation: sourceLocation)
        for (got, want) in zip(path.segments, expected) {
            let ok = Self.sameKind(got, want)
                && zip(Self.points(of: got), Self.points(of: want)).allSatisfy {
                    abs($0.x - $1.x) < 0.01 && abs($0.y - $1.y) < 0.01
                }
            #expect(ok, "\(label): got \(got), expected \(want)", sourceLocation: sourceLocation)
        }
    }

    // MARK: - Outlines

    @Test("Every glyph matches fontTools' reading, in both loca formats",
          arguments: ["CeolKitTest-Short", "CeolKitTest-Long"])
    func outlinesMatchReference(_ file: String) throws {
        let reference = try #require(try Self.references()["\(file).ttf"])
        #expect(reference.indexToLocFormat == (file.hasSuffix("Long") ? 1 : 0))
        let font = try OpenTypeFont.parse(try Self.fixture(file, "ttf"))
        #expect(font.unitsPerEm == Double(reference.unitsPerEm))

        for (code, glyph) in reference.glyphs {
            let scalar = try #require(UInt32(code).flatMap(Unicode.Scalar.init))
            let id = try #require(font.glyphID(for: scalar), "no glyph for \(glyph.name)")
            #expect(font.advance(forGlyph: id) == glyph.advance)
            let expected = try glyph.segments.map(Self.segment)
            expectMatches(try font.outline(forGlyph: id), expected, "\(file) \(glyph.name)")
        }
    }

    @Test("Implied points, an off-curve start and an all-off-curve contour come out as Q")
    func quadraticPathData() throws {
        let font = try OpenTypeFont.parse(try Self.fixture("CeolKitTest-Short", "ttf"))
        let o = try font.outline(forGlyph: try #require(font.glyphID(for: "O")))
        #expect(o.pathData == "M450 175Q300 0 150 175Q0 350 150 525Q300 700 450 525Q600 350 450 175Z")
    }

    @Test("A point-matched component is left out; the rest of the composite is drawn")
    func pointMatchingIsSkipped() throws {
        let font = try OpenTypeFont.parse(try Self.fixture("CeolKitTest-Short", "ttf"))
        let a = try font.outline(forGlyph: try #require(font.glyphID(for: "A")))
        let egrave = try font.outline(forGlyph: try #require(font.glyphID(for: "È")))
        #expect(egrave == a)
    }

    @Test("A composite that includes itself is refused, not followed forever")
    func compositeCycleIsRefused() throws {
        var bytes = [UInt8](try Self.fixture("CeolKitTest-Short", "ttf"))
        let font = try OpenTypeFont.parse(Data(bytes))
        let aacute = try #require(font.glyphID(for: "Á"))

        // Point Aacute's first component at Aacute.
        func u16(_ o: Int) -> Int { Int(bytes[o]) << 8 | Int(bytes[o + 1]) }
        func u32(_ o: Int) -> Int { u16(o) << 16 | u16(o + 2) }
        var tables: [String: Int] = [:]
        for i in 0..<u16(4) {
            let record = 12 + 16 * i
            tables[String(decoding: bytes[record..<(record + 4)], as: UTF8.self)] = u32(record + 8)
        }
        let glyf = try #require(tables["glyf"]), loca = try #require(tables["loca"])
        let glyph = glyf + 2 * u16(loca + 2 * aacute)       // short loca
        #expect(Int16(truncatingIfNeeded: u16(glyph)) < 0)  // a composite
        bytes[glyph + 12] = UInt8(aacute >> 8)
        bytes[glyph + 13] = UInt8(aacute & 0xFF)

        let cyclic = try OpenTypeFont.parse(Data(bytes))
        #expect(throws: OpenTypeError.compositeTooDeep) {
            try cyclic.outline(forGlyph: aacute)
        }
    }

    // MARK: - Collections

    @Test("A collection lists its faces by PostScript name")
    func collectionNames() throws {
        #expect(try OpenTypeFont.postScriptNames(in: try Self.fixture("CeolKitTest", "ttc"))
                == ["CeolKitTest-Regular", "CeolKitTest-Restricted"])
        #expect(try OpenTypeFont.postScriptNames(in: try Self.fixture("CeolKitTest-Short", "ttf"))
                == ["CeolKitTest-Regular"])
    }

    @Test("A face is chosen from a collection by index and by PostScript name")
    func collectionFaceSelection() throws {
        let data = try Self.fixture("CeolKitTest", "ttc")
        #expect(try OpenTypeFont.parse(data).postScriptName == "CeolKitTest-Regular")
        #expect(try OpenTypeFont.parse(data, faceIndex: 1).postScriptName
                == "CeolKitTest-Restricted")
        let byName = try OpenTypeFont.parse(data, postScriptName: "CeolKitTest-Restricted")
        #expect(byName.postScriptName == "CeolKitTest-Restricted")
        #expect(throws: OpenTypeError.faceNotFound("#2")) {
            try OpenTypeFont.parse(data, faceIndex: 2)
        }
        #expect(throws: OpenTypeError.faceNotFound("Helvetica-Bold")) {
            try OpenTypeFont.parse(data, postScriptName: "Helvetica-Bold")
        }

        // Both faces outline: a collection's table offsets are from the start of the file.
        let reference = try #require(try Self.references()["CeolKitTest-Short.ttf"])
        for face in [0, 1] {
            let font = try OpenTypeFont.parse(data, faceIndex: face)
            let glyph = try #require(reference.glyphs["65"])
            expectMatches(try font.outline(forGlyph: try #require(font.glyphID(for: "A"))),
                          try glyph.segments.map(Self.segment), "face \(face) A")
        }
    }

    // MARK: - Embedding permissions

    @Test("fsType is read, and a restricted face may not be outlined into a document")
    func embeddingPermissions() throws {
        let data = try Self.fixture("CeolKitTest", "ttc")
        let open = try OpenTypeFont.parse(data, faceIndex: 0).embedding
        let restricted = try OpenTypeFont.parse(data, faceIndex: 1).embedding
        #expect(open.fsType == 0 && open.allowsOutlineEmbedding)
        #expect(restricted.fsType == 0x0002 && restricted.isRestricted)
        #expect(!restricted.allowsOutlineEmbedding)
    }

    @Test("fsType bits decode as the OS/2 specification has them")
    func fsTypeBits() {
        // Preview & Print and Editable both lift Restricted where set alongside it.
        #expect(!EmbeddingPermissions(fsType: 0x0006).isRestricted)
        #expect(!EmbeddingPermissions(fsType: 0x000A).isRestricted)
        #expect(EmbeddingPermissions(fsType: 0x0004).allowsOutlineEmbedding)
        #expect(!EmbeddingPermissions(fsType: 0x0100).allowsOutlineEmbedding)  // no subsetting
        #expect(!EmbeddingPermissions(fsType: 0x0200).allowsOutlineEmbedding)  // bitmap only
    }

    @Test("The bundled CFF faces are still read, and may be outlined",
          arguments: CeolKitFonts.Face.allCases)
    func bundledFacesUnchanged(_ face: CeolKitFonts.Face) throws {
        let font = try OpenTypeFont.parse(try CeolKitFonts.data(for: face))
        #expect(font.embedding.allowsOutlineEmbedding)
        #expect(font.postScriptName?.isEmpty == false)
        #expect(font.glyphCount > 0)
    }

    // MARK: - Real faces

    #if canImport(CoreText)
    /// Fonts that ship with macOS, where present: real TrueType outlines with every quirk a
    /// production face has, checked against CoreText's own reading of the same file.
    private static let systemFaces = [
        "/System/Library/Fonts/Supplemental/Courier New.ttf",
        "/System/Library/Fonts/Supplemental/Times New Roman.ttf",
    ]

    @Test("System TrueType faces outline as CoreText draws them",
          .enabled(if: systemFaces.contains { FileManager.default.fileExists(atPath: $0) }))
    func systemFacesMatchCoreText() throws {
        for path in Self.systemFaces where FileManager.default.fileExists(atPath: path) {
            let data = try Data(contentsOf: URL(fileURLWithPath: path))
            let font = try OpenTypeFont.parse(data)
            let descriptors = try #require(
                CTFontManagerCreateFontDescriptorsFromData(data as CFData) as? [CTFontDescriptor])
            let ctFont = CTFontCreateWithFontDescriptor(
                try #require(descriptors.first), CGFloat(font.unitsPerEm), nil)

            // Letters, an accented letter (a composite in both faces), and punctuation.
            for character in "AgQé&ß" {
                let scalar = try #require(character.unicodeScalars.first)
                let ours = try #require(font.glyphID(for: scalar))
                var utf16 = Array(String(character).utf16)
                var theirs = [CGGlyph](repeating: 0, count: utf16.count)
                #expect(CTFontGetGlyphsForCharacters(ctFont, &utf16, &theirs, utf16.count))
                #expect(ours == Int(theirs[0]), "\(path) \(character)")

                let path = try font.outline(forGlyph: ours)
                let cgPath = try #require(CTFontCreatePathForGlyph(ctFont, theirs[0], nil))
                let box = cgPath.boundingBox
                let points = path.segments.flatMap(Self.points)
                let xs = points.map(\.x), ys = points.map(\.y)
                let tolerance = 1.0
                #expect(abs((xs.min() ?? 0) - box.minX) < tolerance, "\(character) minX")
                #expect(abs((xs.max() ?? 0) - box.maxX) < tolerance, "\(character) maxX")
                #expect(abs((ys.min() ?? 0) - box.minY) < tolerance, "\(character) minY")
                #expect(abs((ys.max() ?? 0) - box.maxY) < tolerance, "\(character) maxY")
            }
        }
    }
    #endif
}
